### ISSUE TITLE
Unexpected server response: 401

### ISSUE THREAD

**Issue by borahanarslan** [Nafidinara/bot-pancakeswap#107]
Hi, 
I bought a paid api from https://www.ankr.com/ but it still gives the same error, sometimes it does and sometimes it doesn't. What could be the source of the problem

`Listening for Liquidity Addition to token 0x2b3f34e9d4b127797ce6244ea341a83733ddd6e4
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected server response: 401
    at ClientRequest.<anonymous> (C:\Users\borah\Desktop\bot\node_modules\ws\lib\websocket.js:604:7)
    at ClientRequest.emit (node:events:390:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:623:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:487:22)
    at TLSSocket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:234:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
Emitted 'error' event on WebSocket instance at:
    at abortHandshake (C:\Users\borah\Desktop\bot\node_modules\ws\lib\websocket.js:731:15)
    at ClientRequest.<anonymous> (C:\Users\borah\Desktop\bot\node_modules\ws\lib\websocket.js:604:7)
    [... lines matching original stack trace ...]
    at TLSSocket.Readable.push (node:internal/streams/readable:234:10)

Node.js v17.2.0

C:\Users\borah\Desktop\bot>`

**Comment by Nafidinara** [comment]
hi @borahanarslan what package node that you buy from ankr?
