### ISSUE TITLE
I keep getting this error

### ISSUE THREAD

**Issue by Useruses** [Nafidinara/bot-pancakeswap#4]
Error: invalid hexlify value (argument="value", value="my mnemonic", code=INVALID_ARGUMENT, version=bytes/5.1.0)
    at Logger.makeError (C:\Users\comp\Downloads\update-bot\node_modules\@ethersproject\logger\lib\index.js:180:21)
    at Logger.throwError (C:\Users\com\Downloads\update-bot\node_modules\@ethersproject\logger\lib\index.js:189:20)
    at Logger.throwArgumentError (C:\Users\comp\Downloads\update-bot\node_modules\@ethersproject\logger\lib\index.js:192:21)
    at Object.hexlify (C:\Users\comp\Downloads\update-bot\node_modules\@ethersproject\bytes\lib\index.js:190:19)
    at new SigningKey (C:\Users\comp\Downloads\update-bot\node_modules\@ethersproject\signing-key\lib\index.js:20:65)
    at new Wallet (C:\Users\comp\Downloads\update-bot\node_modules\@ethersproject\wallet\lib\index.js:123:36)
    at file:///C:/Users/comp/Downloads/update-bot/bot.js:38:16
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:177:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  reason: 'invalid hexlify value',
  code: 'INVALID_ARGUMENT',
  argument: 'value',
  value: 'my mnemonic'
}

**Comment by Nafidinara** [comment]
Put your private key on mnemonic variable, then run again

**Comment by Useruses** [comment]
I already have put it, I just replaced it with "my mnemonic" in the error code.
Here is how the line 22 looks, (my mnenomic instead of the private key):
const mnemonic = 'my mnemonic'

**Comment by Nafidinara** [comment]
try to see this reference : https://github.com/ethers-io/ethers.js/issues/1166

**Comment by Useruses** [comment]
> try to see this reference : [ethers-io/ethers.js#1166](https://github.com/ethers-io/ethers.js/issues/1166)

Ok thank you.
