### ISSUE TITLE
Error: invalid hexlify value (argument="value", value="my seed phrase", code=INVALID_ARGUMENT, version=bytes/5.4.0)

### ISSUE THREAD

**Issue by pierreabichacra** [Nafidinara/bot-pancakeswap#52]
node bot.js
/Users/myname/Desktop/bot-pancakeswap/node_modules/@ethersproject/logger/lib/index.js:196
        throw this.makeError(message, code, params);
        ^

Error: invalid hexlify value (argument="value", value="my seed phrase", code=INVALID_ARGUMENT, version=bytes/5.4.0)
    at Logger.makeError (/Users/myname/Desktop/bot-pancakeswap/node_modules/@ethersproject/logger/lib/index.js:187:21)
    at Logger.throwError (/Users/myname/Desktop/bot-pancakeswap/node_modules/@ethersproject/logger/lib/index.js:196:20)
    at Logger.throwArgumentError (/Users/myname/Desktop/bot-pancakeswap/node_modules/@ethersproject/logger/lib/index.js:199:21)
    at Object.hexlify (/Users/myname/Desktop/bot-pancakeswap/node_modules/@ethersproject/bytes/lib/index.js:197:19)
    at new SigningKey (/Users/myname/Desktop/bot-pancakeswap/node_modules/@ethersproject/signing-key/lib/index.js:20:65)
    at new Wallet (/Users/myname/Desktop/bot-pancakeswap/node_modules/@ethersproject/wallet/lib/index.js:123:36)
    at Object.<anonymous> (/Users/myname/Desktop/bot-pancakeswap/bot.js:42:16)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32) {
  reason: 'invalid hexlify value',
  code: 'INVALID_ARGUMENT',
  argument: 'value',
  value: 'my seed phrase'
}
NB: the seed phrase is correct
package.json:{
  "name": "trading-bot",
  "version": "1.0.0",
  "description": "",
  "main": "bot.js",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "snipe": "node bot.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "chalk": "^4.1.1",
    "dotenv": "^10.0.0",
    "ethers": "^5.1.4",
    "express": "^4.17.1",
    "inquirer": "^8.1.0"
  }
}

**Comment by Nafidinara** [comment]
you need to put private key instead seed word
