### ISSUE TITLE
erroring out during run snipe.bsc  TypeError

### ISSUE THREAD

**Issue by harpua216** [Nafidinara/bot-pancakeswap#64]
hello, i cam getting this error when trying to reinstall
$ npm run snipe-bsc

> trading-bot@1.0.0 snipe-bsc
> node -r dotenv/config snipe.js dotenv_config_path=./.env.bsc

TypeError: Cannot read property 'toString' of undefined
    at file:///C:/New/sonic-advanced-bot-master/snipe.js:1:18233
    at ModuleJob.run (internal/modules/esm/module_job.js:169:25)
    at async Loader.import (internal/modules/esm/loader.js:177:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)

thanks

**Comment by Nafidinara** [comment]
hi, you can only type with 'npm run snipe' command
