### ISSUE TITLE
npm ERR! code ELIFECYCLE

### ISSUE THREAD

**Issue by amondays** [Nafidinara/bot-pancakeswap#69]
C:\bot\1>npm run snipe

> trading-bot@1.0.0 snipe C:\bot\1
> node bot.js

Listening for Liquidity Addition to token 0x5ee36c0a5e96220f9dcde6a068c5f4e597f83fbb
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected server response: 503
    at ClientRequest.<anonymous> (C:\bot\1\node_modules\ws\lib\websocket.js:580:7)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:204:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
Emitted 'error' event on WebSocket instance at:
    at abortHandshake (C:\bot\1\node_modules\ws\lib\websocket.js:698:15)
    at ClientRequest.<anonymous> (C:\bot\1\node_modules\ws\lib\websocket.js:580:7)
    [... lines matching original stack trace ...]
    at TLSSocket.Readable.push (internal/streams/readable.js:204:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! trading-bot@1.0.0 snipe: `node bot.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the trading-bot@1.0.0 snipe script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dev\AppData\Roaming\npm-cache\_logs\2021-08-01T09_34_04_613Z-debug.log

**Comment by amondays** [comment]
What could be the problem? It still 1x worked yesterday..

**Comment by Nafidinara** [comment]
Its problem with public node, you can change the WSS_NODE with private node
or full node

Pada tanggal Min, 1 Agu 2021 16.35, amondays ***@***.***>
menulis:

**Comment by Nafidinara** [comment]
HI, I see many of yours get same problem, check this to solve : https://github.com/Nafidinara/bot-pancakeswap#TROUBLESHOOT
