### ISSUE TITLE
Call Revert Exception

### ISSUE THREAD

**Issue by cem-altuner** [Nafidinara/bot-pancakeswap#70]
When I trying to purchase this error occurs bruh. What I am gonna do?

```
(node:24244) UnhandledPromiseRejectionWarning: Error: call revert exception (method="getPair(address,address)", errorSignature=null, errorArgs=[null], reason=null, code=CALL_EXCEPTION, version=abi/5.1.2)
    at Logger.makeError (C:\Users\cemal\OneDrive\Masaüstü\bot-pancakeswap-master\node_modules\@ethersproject\logger\lib\index.js:180:21)
    at Logger.throwError (C:\Users\cemal\OneDrive\Masaüstü\bot-pancakeswap-master\node_modules\@ethersproject\logger\lib\index.js:189:20)
    at Interface.decodeFunctionResult (C:\Users\cemal\OneDrive\Masaüstü\bot-pancakeswap-master\node_modules\@ethersproject\abi\lib\interface.js:289:23)
    at Contract.<anonymous> (C:\Users\cemal\OneDrive\Masaüstü\bot-pancakeswap-master\node_modules\@ethersproject\contracts\lib\index.js:329:56)
    at step (C:\Users\cemal\OneDrive\Masaüstü\bot-pancakeswap-master\node_modules\@ethersproject\contracts\lib\index.js:48:23)
    at Object.next (C:\Users\cemal\OneDrive\Masaüstü\bot-pancakeswap-master\node_modules\@ethersproject\contracts\lib\index.js:29:53)
    at fulfilled (C:\Users\cemal\OneDrive\Masaüstü\bot-pancakeswap-master\node_modules\@ethersproject\contracts\lib\index.js:20:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:24244) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24244) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Nafidinara** [comment]
Seems you're wrong input the settings

Pada tanggal Min, 1 Agu 2021 19.09, cem-altuner ***@***.***>
menulis:
