### ISSUE TITLE
wss error

### ISSUE THREAD

**Issue by DUya98** [Nafidinara/bot-pancakeswap#71]
```
node:events:346
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::5001
    at Server.setupListenHandle [as _listen2] (node:net:1310:16)
    at listenInCluster (node:net:1358:12)
    at Server.listen (node:net:1445:7)
    at Function.listen (/Users/zhong/Downloads/bot-pancakeswap-master/node_modules/express/lib/application.js:618:24)
    at file:///Users/zhong/Downloads/bot-pancakeswap-master/bot.js:196:5
    at ModuleJob.run (node:internal/modules/esm/module_job:154:23)
    at async Loader.import (node:internal/modules/esm/loader:166:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1337:8)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 5001
}

```json
WSS_NODE=wss://bsc-ws-node.nariox.org:443

503 is displayed if an exception is thrown

**Comment by Nafidinara** [comment]
HI, I see many of yours get some problem, check this to solve : https://github.com/Nafidinara/bot-pancakeswap#TROUBLESHOOT
