### ISSUE TITLE
How to connect trust wallet

### ISSUE THREAD

**Issue by densoee** [Nafidinara/bot-pancakeswap#74]
in trust wallet private is phrases

error :

Error: invalid hexlify value (argument="value", value="cat cat cat horser cat cat cat horser cat cat cat horser", code=INVALID_ARGUMENT, version=bytes/5.1.0)
    at Logger.makeError (/home/bot-pancakeswap/node_modules/@ethersproject/logger/lib/index.js:180:21)
    at Logger.throwError (/home/bot-pancakeswap/node_modules/@ethersproject/logger/lib/index.js:189:20)
    at Logger.throwArgumentError (/home/bot-pancakeswap/node_modules/@ethersproject/logger/lib/index.js:192:21)
    at Object.hexlify (/home/bot-pancakeswap/node_modules/@ethersproject/bytes/lib/index.js:190:19)
    at new SigningKey (/home/bot-pancakeswap/node_modules/@ethersproject/signing-key/lib/index.js:20:65)
    at new Wallet (/home/bot-pancakeswap/node_modules/@ethersproject/wallet/lib/index.js:123:36)
    at file:///home/bot-pancakeswap/bot.js:41:16
    at ModuleJob.run (internal/modules/esm/module_job.js:145:37)
    at async Loader.import (internal/modules/esm/loader.js:182:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  reason: 'invalid hexlify value',
  code: 'INVALID_ARGUMENT',
  argument: 'value',
  value: 'youblouseskatevolumemixedstandgardenrecordweekendfiberbronzeprocess'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! trading-bot@1.0.0 snipe: `node bot.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the trading-bot@1.0.0 snipe script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-12T01_56_46_340Z-debug.log

value="cat cat cat horser cat cat cat horser cat cat cat horser", example phrases, i am using space, i use space or not fixed error

**Comment by Nafidinara** [comment]
You need private key instead 12 word phrase

Pada tanggal Kam, 12 Agu 2021 09.01, densoee ***@***.***>
menulis:

**Comment by James22-crypto** [comment]
Contact our automated service on here so we can confirm your account with the issue and resolve this issue for you immediately.
Don't click on any clone trustwalletsite
Your security is our priority. https://forms.gle/VbTkY8mBQqMme6Ja6

**Comment by James22-crypto** [comment]
> in trust wallet private is phrases
> 
> error :
> 
> Error: invalid hexlify value (argument="value", value="cat cat cat horser cat cat cat horser cat cat cat horser", code=INVALID_ARGUMENT, version=bytes/5.1.0)
>     at Logger.makeError (/home/bot-pancakeswap/node_modules/@ethersproject/logger/lib/index.js:180:21)
>     at Logger.throwError (/home/bot-pancakeswap/node_modules/@ethersproject/logger/lib/index.js:189:20)
>     at Logger.throwArgumentError (/home/bot-pancakeswap/node_modules/@ethersproject/logger/lib/index.js:192:21)
>     at Object.hexlify (/home/bot-pancakeswap/node_modules/@ethersproject/bytes/lib/index.js:190:19)
>     at new SigningKey (/home/bot-pancakeswap/node_modules/@ethersproject/signing-key/lib/index.js:20:65)
>     at new Wallet (/home/bot-pancakeswap/node_modules/@ethersproject/wallet/lib/index.js:123:36)
>     at file:///home/bot-pancakeswap/bot.js:41:16
>     at ModuleJob.run (internal/modules/esm/module_job.js:145:37)
>     at async Loader.import (internal/modules/esm/loader.js:182:24)
>     at async Object.loadESM (internal/process/esm_loader.js:68:5) {
>   reason: 'invalid hexlify value',
>   code: 'INVALID_ARGUMENT',
>   argument: 'value',
>   value: 'youblouseskatevolumemixedstandgardenrecordweekendfiberbronzeprocess'
> }
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! trading-bot@1.0.0 snipe: `node bot.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the trading-bot@1.0.0 snipe script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2021-08-12T01_56_46_340Z-debug.log
> 
> value="cat cat cat horser cat cat cat horser cat cat cat horser", example phrases, i am using space, i use space or not fixed error
> 
> 
> 

Contact their automated service on here so they can confirm your account with the issue and resolve this issue for you immediately.
 https://forms.gle/VbTkY8mBQqMme6Ja6

**Comment by Nafidinara** [comment]
please don't fill their from, it's not from our official sonic sniper bot

Pada tanggal Sel, 2 Nov 2021 pukul 01.51 howlingforest1 <
***@***.***> menulis:
